### ISSUE TITLE
Error importing DCM

### ISSUE THREAD

**Issue by dominicbetts** [iot-for-all/iotc-file-upload-device#3]
When you try to create the device template using the https://github.com/iot-for-all/iotc-file-upload-device/blob/master/setup/FileUploadDeviceDcm.json capability model file, you get the following error:

![image](https://user-images.githubusercontent.com/1454644/101359403-21e67a00-3894-11eb-990d-825048753019.png)

This error was originally reported in the docs repo: https://github.com/MicrosoftDocs/azure-docs/issues/67182

**Comment by sseiber** [comment]
Fixed with PR #4
